
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CanvasRespondRule
{

    public int CanvasRuleId { get; set; }

    public Nullable<byte> CanvasRuleForId { get; set; }

    public string CanvasRuleTitle { get; set; }

    public string CanvasAnswer { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

}

}
