
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cours
{

    public System.Guid CourseId { get; set; }

    public string CourseName { get; set; }

    public string CourseDescription { get; set; }

    public System.DateTime CourseCreateDate { get; set; }

    public Nullable<System.Guid> CreatedBy { get; set; }

    public Nullable<System.Guid> Updatedby { get; set; }

    public Nullable<int> CanvasId { get; set; }

}

}
