
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CourseProvider
{

    public System.Guid Id { get; set; }

    public Nullable<System.Guid> CourseId { get; set; }

    public Nullable<System.Guid> ProviderId { get; set; }

}

}
