
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DiscussionDetail
{

    public System.Guid DiscussionDetailId { get; set; }

    public string DiscussionComments { get; set; }

    public Nullable<System.Guid> DiscussionId { get; set; }

    public Nullable<System.Guid> EnteredBy { get; set; }

}

}
