
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FAQEmailsDownload
{

    public int faq_email_download_id { get; set; }

    public int faq_email_id { get; set; }

    public string email_uid { get; set; }

    public System.DateTime download_date { get; set; }

}

}
