
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    public System.Guid QuestionId { get; set; }

    public Nullable<int> QuestionType { get; set; }

    public string QuestionDesc { get; set; }

}

}
