
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SmtpPopSetting
{

    public int smtp_pop_id { get; set; }

    public string setting_name { get; set; }

    public string smtp_server { get; set; }

    public int smpt_port { get; set; }

    public bool smtp_use_ssl { get; set; }

    public string pop_server { get; set; }

    public int pop_port { get; set; }

    public bool pop_use_ssl { get; set; }

    public Nullable<bool> active { get; set; }

}

}
