
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StudentRegistration
{

    public int ID { get; set; }

    public int StudentID { get; set; }

    public System.Guid CourseID { get; set; }

    public System.Guid UniversityID { get; set; }

}

}
