
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubDiscussionDetail
{

    public System.Guid id { get; set; }

    public Nullable<System.Guid> SubDiscussionId { get; set; }

    public string SubDiscussionSubject { get; set; }

    public string SubDiscussionDetail1 { get; set; }

}

}
