
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubDiscussionReply
{

    public Nullable<System.Guid> SubDiscussionDetailId { get; set; }

    public string ReplyFrom { get; set; }

    public string ReplyContent { get; set; }

    public System.Guid Id { get; set; }

}

}
