
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubKnowDiscussion
{

    public System.Guid Id { get; set; }

    public int DiscussionId { get; set; }

    public Nullable<System.Guid> CourseId { get; set; }

    public string DiscussionURL { get; set; }

    public string Originator { get; set; }

    public Nullable<bool> IsNewDiscussion { get; set; }

    public int NumerOfReplies { get; set; }

    public string LastPostedBy { get; set; }

    public bool IsPostReplied { get; set; }

    public string SubTopic { get; set; }

}

}
