
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UnAnsweredFAQ
{

    public int unanswered_faq_id { get; set; }

    public string faq { get; set; }

    public Nullable<int> faq_answered_id { get; set; }

    public string faq_answer { get; set; }

    public Nullable<int> faq_email_id { get; set; }

    public string to_email_address { get; set; }

    public string faq_email_subject { get; set; }

}

}
